# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/livesttt/__main__.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/livesttt', 'livesttt'),
        (r'.venv\Lib\site-packages\_sounddevice_data', '_sounddevice_data'),
    ],
    hiddenimports=[
        'cv2',
        'PIL',
        'pystray',
        'pyautogui',
        'pyperclip',
        'sounddevice',
        'numpy',
        'pydub',
        'requests',
        'loguru',
        'transformers',
        'torch',
        'scipy',
        'scipy.signal',
        'pystray._win32',
        'PIL._tkinter_finder',
        'win32api',
        'win32con',
        'win32gui',
        'pythoncom',
        'pywintypes',
        'pyautogui._pyautogui_win',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='livesttt',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=['pywintypes*.dll', 'vcruntime*.dll'],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)